export const COMPANY = {
  name: 'JS Empregos',
  tradingName: 'JS Terceirizados',
  brand: 'JS Empregos',
  cnpj: '00.000.000/0001-00',
  phone: '(11) 96838-0592',
  email: 'contato@jrtelempregos.com.br',
  whatsapp: '5511968380592',
  description:
    'Agência de Empregos e Assessoria em Recursos Humanos. Mais eficiência em RH. Mais resultados para sua empresa. Conectamos empresas aos melhores profissionais por meio de recrutamento, seleção, banco de talentos e hunting.',
  tagline: 'Mais eficiência em RH. Mais resultados para sua empresa.',
  address: {
    street: 'Rodovia João Afonso de Souza Castellano',
    number: '411',
    complement: 'Sala n° 04',
    neighborhood: 'Poá',
    city: 'Poá',
    state: 'SP',
    country: 'Brasil',
    zip: '',
  },
  businessAreas: [
    'Recrutamento e Seleção',
    'Banco de Talentos',
    'Hunting de Executivos',
    'Avaliação de Perfil',
    'Mão de Obra Temporária',
    'Mão de Obra Efetiva',
    'Processo de RH',
    'Terceirização de Serviços',
    'Limpeza',
    'Segurança Patrimonial',
    'Portaria',
    'Jardinagem e Paisagismo',
    'Zeladoria',
    'Facilities',
  ],
  yearsOfExperience: 15,
  clientsServed: 200,
  professionals: 500,
  citiesCovered: 50,
} as const;

export const SOCIAL_LINKS = {
  instagram: 'https://instagram.com/jrtelempregos',
  facebook: 'https://facebook.com/jrtelempregos',
  tiktok: 'https://tiktok.com/@jrtelempregos',
  linkedin: 'https://linkedin.com/company/jrtelempregos',
  youtube: 'https://youtube.com/@jrtelempregos',
  twitter: 'https://twitter.com/jrtelempregos',
  whatsapp: 'https://wa.me/5511968380592',
  email: 'mailto:contato@jrtelempregos.com.br',
} as const;
